package com.ayronasystems.core.backtest;

/**
 * Created by gorkemgok on 29/08/16.
 */
public enum ResultQuantaMetric {

    EQUITY,
    NET_PROFIT,
    GROSS_PROFIT,
    GROSS_LOSS,
    EQUITY_PERCENTAGE,
    NET_PROFIT_PERCENTAGE,
    GROSS_PROFIT_PERCENTAGE,
    GROSS_LOSS_PERCENTAGE,
    PROFIT_FACTOR,

    MDD,
    MDD_PERCENTAGE,

    TOTAL_NUMBER_OF_TRADES,
    WINNING_TRADE_COUNT,
    LOSING_TRADE_COUNT,
    PROFITABLE_PERCENT,

    AVE_NET_PROFIT,
    AVE_WINNING_TRADE,
    AVE_LOSING_TRADE,
    RATIO_AVE_WINNING_LOSING,
    LARGEST_WINNING_TRADE,
    LARGEST_LOSING_TRADE,

    AVE_NET_PROFIT_PERCENT,
    AVE_WINNING_TRADE_PERCENT,
    AVE_LOSING_TRADE_PERCENT,
    RATIO_AVE_WINNING_LOSING_PERCENT,
    LARGEST_WINNING_TRADE_PERCENT,
    LARGEST_LOSING_TRADE_PERCENT,

    MAX_CONSECUTIVE_WINNING_TRADES,
    MAX_CONSECUTIVE_LOSING_TRADES,
    AVE_BARS_IN_WINNING_TRADES,
    AVE_BARS_IN_LOSING_TRADES
    
}
